"""Add payment_proof_url to orders

Revision ID: 0687e62fcc6e
Revises: e8d27793066b
Create Date: 2025-08-18 20:06:47.354786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0687e62fcc6e'
down_revision = 'e8d27793066b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_proof_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('customer_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('customer_phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('customer_phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('customer_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('payment_proof_url')

    # ### end Alembic commands ###
