"""Add ON DELETE CASCADE to category_id foreign key in products

Revision ID: 12ecae679517
Revises: 77930d1f0536
Create Date: 2025-07-19 13:36:38.390077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ecae679517'
down_revision = '77930d1f0536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('discount_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('discount_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('carts',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('saved_for_later', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.cart_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_1', 'categories', ['category_id'], ['category_id'])

    op.drop_table('cart_items')
    op.drop_table('carts')
    op.drop_table('discounts')
    # ### end Alembic commands ###
