"""Describe your changes here

Revision ID: 7532a5052ae6
Revises: fe7a363f5d2d
Create Date: 2025-08-12 12:45:07.110444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7532a5052ae6'
down_revision = 'fe7a363f5d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('momo_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('momo_network', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('special_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('special_notes')
        batch_op.drop_column('momo_network')
        batch_op.drop_column('momo_number')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('city')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
