"""Add image_url to products

Revision ID: 77930d1f0536
Revises: 72ff4dfd16b9
Create Date: 2025-07-13 18:44:42.571389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77930d1f0536'
down_revision = '72ff4dfd16b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
