"""Add status and reply tracking fields to ContactMessage

Revision ID: 83f110626ae3
Revises: 1cc050b421b9
Create Date: 2025-07-26 17:48:07.413778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83f110626ae3'
down_revision = '1cc050b421b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('replied_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('replied_by_user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('date_sent',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['replied_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date_sent',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('replied_by_user_id')
        batch_op.drop_column('replied_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
