"""Add required customer info fields to orders table

Revision ID: e8d27793066b
Revises: 7532a5052ae6
Create Date: 2025-08-16 16:00:04.536106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8d27793066b'
down_revision = '7532a5052ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('customer_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('customer_phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('customer_phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('customer_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
